apiVersion: v1
kind: Secret
metadata:
  name: vacancy-secrets
  namespace: vacancy-scout
  labels:
    app.kubernetes.io/part-of: vacancy-scout
type: Opaque
stringData:
  db-password: "vacancy_scout"
  r2dbc-url: "r2dbc:postgresql://vacancy-scout-db.vacancy-scout.svc.cluster.local:5432/vacancy_scout"
  db-host: "vacancy-scout-db.vacancy-scout.svc.cluster.local"
  redis-host: "vacancy-scout-redis.vacancy-scout.svc.cluster.local"
  db-username: "vacancy_scout"
  db-name: "vacancy_scout"
  db-port: "5432"
  redis-port: "6379"
