spring:
  application:
    name: vacancy-scout
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/vacancy_scout
    username: vacancy_scout
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev
  main:
    web-application-type: reactive

server:
  port: 8080
